[package]
name = "crypto-accounting-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name="balance_sheet"
path = "src/lib.rs"
crate-type = ["lib"]
required-features = [] 